// <auto-generated />
using System;
using FourFoldAccountManager.Leaderboard.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FourFoldAccountManager.Leaderboard.Service.Data.Migrations
{
    [DbContext(typeof(LeaderboardDbContext))]
    [Migration("20260923194212_InitialLeaderboard")]
    partial class InitialLeaderboard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FourFoldAccountManager.Leaderboard.Service.Data.InstallationParticipationEntity", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SharingEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("InstallationId");

                    b.ToTable("installation_participation", (string)null);
                });

            modelBuilder.Entity("FourFoldAccountManager.Leaderboard.Service.Data.InstallationProfileEntity", b =>
                {
                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastActiveAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("InstallationId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("IsActive", "LastActiveAtUtc");

                    b.ToTable("installation_profile", (string)null);
                });

            modelBuilder.Entity("FourFoldAccountManager.Leaderboard.Service.Data.PlayerSampleStateEntity", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastSampledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NeedsBaseline")
                        .HasColumnType("boolean");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("PlayerId");

                    b.ToTable("player_sample_state", (string)null);
                });

            modelBuilder.Entity("FourFoldAccountManager.Leaderboard.Service.Data.XpGainEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Gain")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ObservedAtUtc", "PlayerId");

                    b.ToTable("xp_gain_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_positive_gain", "\"Gain\" > 0");
                        });
                });

            modelBuilder.Entity("FourFoldAccountManager.Leaderboard.Service.Data.InstallationProfileEntity", b =>
                {
                    b.HasOne("FourFoldAccountManager.Leaderboard.Service.Data.InstallationParticipationEntity", "Installation")
                        .WithMany("Profiles")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("FourFoldAccountManager.Leaderboard.Service.Data.InstallationParticipationEntity", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
